den_chat_homepage:
    path:     /
    defaults: { _controller: DenChatBundle:Default:index }
    
message_new:
    path:     /message_new
    defaults: { _controller: DenChatBundle:Default:new }
    
message_form:
    path:     /message_form
    defaults: { _controller: DenChatBundle:Default:form }

message_edit_ajax:
    path:     /message_edit
    defaults: { _controller: DenChatBundle:Default:editAjax }