app_ann:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /
    
app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /
    
hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect
    
facebook_login:
    pattern: /login/check-facebook