# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    user_class_name: Den\UserBundle\Entity\User
    
services:
    den.aouth_user_provider:
        class: Den\UserBundle\Entity\OAuthUserProvider
        arguments: ["@doctrine", "%user_class_name%"]
