chat:
    resource: "@AppBundle/Controller/ChatController.php"
    type:     annotation
    
user:
    resource: "@AppBundle/Controller/UserController.php"
    type:     annotation
    
secured:
    resource: "@AppBundle/Controller/SecuredController.php"
    type:     annotation
    